### ISSUE TITLE
Not working in bootstrap-vue tabs

### ISSUE THREAD

**Issue by 1zaak** [Justineo/vue-awesome#88]
So I am using the [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue) library but the icon component won't work inside tabs. 

Specifically: 
```
<b-tab :title="`Tab 1 <icon name='minus-square'></icon>`" active>
```

Outside of it, the icon component works and renders to SVG without any problems. 

How do make it render inside the `b-tab` prop?

**Comment by Justineo** [comment]
I looked into [bootstrap-vue](https://github.com/bootstrap-vue/bootstrap-vue)'s source code and it turns out it doesn't support Vue components inside tab titles. Vue-Awesome cannot be used in it unless it support Vue's [scoped slots](https://vuejs.org/v2/guide/components.html#Scoped-Slots). You can make a feature request there.
